package servicelayer.server.dal.pojos;
// Generated Jun 12, 2014 10:23:42 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * AdminRoadReport generated by hbm2java
 */
public class AdminRoadReport  implements java.io.Serializable {


     private Integer id;
     private Admin admin;
     private Road road;
     private ReportTypeLookUp reportTypeLookUp;
     private Date startTimeStamp;
     private Date endTimeStamp;
     private String reportStatus;
     private double blockingRatio;

    public AdminRoadReport() {
    }

	
    public AdminRoadReport(Admin admin, Road road, ReportTypeLookUp reportTypeLookUp, double blockingRatio) {
        this.admin = admin;
        this.road = road;
        this.reportTypeLookUp = reportTypeLookUp;
        this.blockingRatio = blockingRatio;
    }
    public AdminRoadReport(Admin admin, Road road, ReportTypeLookUp reportTypeLookUp, Date startTimeStamp, Date endTimeStamp, String reportStatus, double blockingRatio) {
       this.admin = admin;
       this.road = road;
       this.reportTypeLookUp = reportTypeLookUp;
       this.startTimeStamp = startTimeStamp;
       this.endTimeStamp = endTimeStamp;
       this.reportStatus = reportStatus;
       this.blockingRatio = blockingRatio;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Admin getAdmin() {
        return this.admin;
    }
    
    public void setAdmin(Admin admin) {
        this.admin = admin;
    }
    public Road getRoad() {
        return this.road;
    }
    
    public void setRoad(Road road) {
        this.road = road;
    }
    public ReportTypeLookUp getReportTypeLookUp() {
        return this.reportTypeLookUp;
    }
    
    public void setReportTypeLookUp(ReportTypeLookUp reportTypeLookUp) {
        this.reportTypeLookUp = reportTypeLookUp;
    }
    public Date getStartTimeStamp() {
        return this.startTimeStamp;
    }
    
    public void setStartTimeStamp(Date startTimeStamp) {
        this.startTimeStamp = startTimeStamp;
    }
    public Date getEndTimeStamp() {
        return this.endTimeStamp;
    }
    
    public void setEndTimeStamp(Date endTimeStamp) {
        this.endTimeStamp = endTimeStamp;
    }
    public String getReportStatus() {
        return this.reportStatus;
    }
    
    public void setReportStatus(String reportStatus) {
        this.reportStatus = reportStatus;
    }
    public double getBlockingRatio() {
        return this.blockingRatio;
    }
    
    public void setBlockingRatio(double blockingRatio) {
        this.blockingRatio = blockingRatio;
    }




}


