package servicelayer.server.dal.pojos;
// Generated Jun 12, 2014 10:23:42 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Admin generated by hbm2java
 */
public class Admin  implements java.io.Serializable {


     private Integer id;
     private Roles roles;
     private String name;
     private String email;
     private String username;
     private String password;
     private Set adminRoadReports = new HashSet(0);

    public Admin() {
    }

	
    public Admin(String name, String email, String username, String password) {
        this.name = name;
        this.email = email;
        this.username = username;
        this.password = password;
    }
    public Admin(Roles roles, String name, String email, String username, String password, Set adminRoadReports) {
       this.roles = roles;
       this.name = name;
       this.email = email;
       this.username = username;
       this.password = password;
       this.adminRoadReports = adminRoadReports;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Roles getRoles() {
        return this.roles;
    }
    
    public void setRoles(Roles roles) {
        this.roles = roles;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Set getAdminRoadReports() {
        return this.adminRoadReports;
    }
    
    public void setAdminRoadReports(Set adminRoadReports) {
        this.adminRoadReports = adminRoadReports;
    }




}


