package servicelayer.server.dal.pojos;
// Generated Jun 12, 2014 10:23:42 PM by Hibernate Tools 3.6.0



/**
 * BlockedUser generated by hbm2java
 */
public class BlockedUser  implements java.io.Serializable {


     private int userId;
     private String name;
     private String mobile;
     private String email;
     private String userToken;
     private String tokenType;

    public BlockedUser() {
    }

	
    public BlockedUser(int userId, String tokenType) {
        this.userId = userId;
        this.tokenType = tokenType;
    }
    public BlockedUser(int userId, String name, String mobile, String email, String userToken, String tokenType) {
       this.userId = userId;
       this.name = name;
       this.mobile = mobile;
       this.email = email;
       this.userToken = userToken;
       this.tokenType = tokenType;
    }
   
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getUserToken() {
        return this.userToken;
    }
    
    public void setUserToken(String userToken) {
        this.userToken = userToken;
    }
    public String getTokenType() {
        return this.tokenType;
    }
    
    public void setTokenType(String tokenType) {
        this.tokenType = tokenType;
    }




}


