package servicelayer.server.dal.pojos;
// Generated Jun 12, 2014 10:23:42 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * CarListLookUp generated by hbm2java
 */
public class CarListLookUp  implements java.io.Serializable {


     private Integer carId;
     private String carValue;
     private Set users = new HashSet(0);

    public CarListLookUp() {
    }

	
    public CarListLookUp(String carValue) {
        this.carValue = carValue;
    }
    public CarListLookUp(String carValue, Set users) {
       this.carValue = carValue;
       this.users = users;
    }
   
    public Integer getCarId() {
        return this.carId;
    }
    
    public void setCarId(Integer carId) {
        this.carId = carId;
    }
    public String getCarValue() {
        return this.carValue;
    }
    
    public void setCarValue(String carValue) {
        this.carValue = carValue;
    }
    public Set getUsers() {
        return this.users;
    }
    
    public void setUsers(Set users) {
        this.users = users;
    }




}


