package servicelayer.server.dal.pojos;
// Generated Jun 12, 2014 10:23:42 PM by Hibernate Tools 3.6.0



/**
 * CurrentVersion generated by hbm2java
 */
public class CurrentVersion  implements java.io.Serializable {


     private Integer id;
     private int carListVersion;
     private int fuelTypeListVersion;
     private int mainPointListVersion;
     private int reportTypeVersion;
     private byte[] rsapublicKey;

    public CurrentVersion() {
    }

	
    public CurrentVersion(int carListVersion, int fuelTypeListVersion, int mainPointListVersion, int reportTypeVersion) {
        this.carListVersion = carListVersion;
        this.fuelTypeListVersion = fuelTypeListVersion;
        this.mainPointListVersion = mainPointListVersion;
        this.reportTypeVersion = reportTypeVersion;
    }
    public CurrentVersion(int carListVersion, int fuelTypeListVersion, int mainPointListVersion, int reportTypeVersion, byte[] rsapublicKey) {
       this.carListVersion = carListVersion;
       this.fuelTypeListVersion = fuelTypeListVersion;
       this.mainPointListVersion = mainPointListVersion;
       this.reportTypeVersion = reportTypeVersion;
       this.rsapublicKey = rsapublicKey;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getCarListVersion() {
        return this.carListVersion;
    }
    
    public void setCarListVersion(int carListVersion) {
        this.carListVersion = carListVersion;
    }
    public int getFuelTypeListVersion() {
        return this.fuelTypeListVersion;
    }
    
    public void setFuelTypeListVersion(int fuelTypeListVersion) {
        this.fuelTypeListVersion = fuelTypeListVersion;
    }
    public int getMainPointListVersion() {
        return this.mainPointListVersion;
    }
    
    public void setMainPointListVersion(int mainPointListVersion) {
        this.mainPointListVersion = mainPointListVersion;
    }
    public int getReportTypeVersion() {
        return this.reportTypeVersion;
    }
    
    public void setReportTypeVersion(int reportTypeVersion) {
        this.reportTypeVersion = reportTypeVersion;
    }
    public byte[] getRsapublicKey() {
        return this.rsapublicKey;
    }
    
    public void setRsapublicKey(byte[] rsapublicKey) {
        this.rsapublicKey = rsapublicKey;
    }




}


