package servicelayer.server.dal.pojos;
// Generated Jun 12, 2014 10:23:42 PM by Hibernate Tools 3.6.0


import java.util.Date;
import servicelayer.server.dal.daos.WinnerDAO;

/**
 * DailyWinner generated by hbm2java
 */
public class DailyWinner  implements java.io.Serializable {


     private Integer id;
     private User user;
     private int noOfSnapshots;
     private Date date;

    public DailyWinner() {
    }

    public DailyWinner(User user, int noOfSnapshots, Date date) {
       this.user = user;
       this.noOfSnapshots = noOfSnapshots;
       this.date = date;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public int getNoOfSnapshots() {
        return this.noOfSnapshots;
    }
    
    public void setNoOfSnapshots(int noOfSnapshots) {
        this.noOfSnapshots = noOfSnapshots;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }


   


}


