package servicelayer.server.dal.pojos;
// Generated Jun 12, 2014 10:23:42 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * DailyErrorRatio generated by hbm2java
 */
public class DailyErrorRatio  implements java.io.Serializable {


     private Integer id;
     private SubRoad subRoad;
     private Date date;
     private double errorRatio;

    public DailyErrorRatio() {
    }

    public DailyErrorRatio(SubRoad subRoad, Date date, double errorRatio) {
       this.subRoad = subRoad;
       this.date = date;
       this.errorRatio = errorRatio;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public SubRoad getSubRoad() {
        return this.subRoad;
    }
    
    public void setSubRoad(SubRoad subRoad) {
        this.subRoad = subRoad;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public double getErrorRatio() {
        return this.errorRatio;
    }
    
    public void setErrorRatio(double errorRatio) {
        this.errorRatio = errorRatio;
    }




}


