package servicelayer.server.dal.pojos;
// Generated Jun 12, 2014 10:23:42 PM by Hibernate Tools 3.6.0



/**
 * History generated by hbm2java
 */
public class History  implements java.io.Serializable {


     private Integer id;
     private DateLookUp dateLookUp;
     private SubRoad subRoad;
     private Double avgSpeed00;
     private Double avgSpeed01;
     private Double avgSpeed02;
     private Double avgSpeed03;
     private Double avgSpeed04;
     private Double avgSpeed05;
     private Double avgSpeed06;
     private Double avgSpeed07;
     private Double avgSpeed08;
     private Double avgSpeed09;
     private Double avgSpeed10;
     private Double avgSpeed11;
     private Double avgSpeed12;
     private Double avgSpeed13;
     private Double avgSpeed14;
     private Double avgSpeed15;
     private Double avgSpeed16;
     private Double avgSpeed17;
     private Double avgSpeed18;
     private Double avgSpeed19;
     private Double avgSpeed20;
     private Double avgSpeed21;
     private Double avgSpeed22;
     private Double avgSpeed23;

    public History() {
    }

	
    public History(DateLookUp dateLookUp, SubRoad subRoad) {
        this.dateLookUp = dateLookUp;
        this.subRoad = subRoad;
    }
    public History(DateLookUp dateLookUp, SubRoad subRoad, Double avgSpeed00, Double avgSpeed01, Double avgSpeed02, Double avgSpeed03, Double avgSpeed04, Double avgSpeed05, Double avgSpeed06, Double avgSpeed07, Double avgSpeed08, Double avgSpeed09, Double avgSpeed10, Double avgSpeed11, Double avgSpeed12, Double avgSpeed13, Double avgSpeed14, Double avgSpeed15, Double avgSpeed16, Double avgSpeed17, Double avgSpeed18, Double avgSpeed19, Double avgSpeed20, Double avgSpeed21, Double avgSpeed22, Double avgSpeed23) {
       this.dateLookUp = dateLookUp;
       this.subRoad = subRoad;
       this.avgSpeed00 = avgSpeed00;
       this.avgSpeed01 = avgSpeed01;
       this.avgSpeed02 = avgSpeed02;
       this.avgSpeed03 = avgSpeed03;
       this.avgSpeed04 = avgSpeed04;
       this.avgSpeed05 = avgSpeed05;
       this.avgSpeed06 = avgSpeed06;
       this.avgSpeed07 = avgSpeed07;
       this.avgSpeed08 = avgSpeed08;
       this.avgSpeed09 = avgSpeed09;
       this.avgSpeed10 = avgSpeed10;
       this.avgSpeed11 = avgSpeed11;
       this.avgSpeed12 = avgSpeed12;
       this.avgSpeed13 = avgSpeed13;
       this.avgSpeed14 = avgSpeed14;
       this.avgSpeed15 = avgSpeed15;
       this.avgSpeed16 = avgSpeed16;
       this.avgSpeed17 = avgSpeed17;
       this.avgSpeed18 = avgSpeed18;
       this.avgSpeed19 = avgSpeed19;
       this.avgSpeed20 = avgSpeed20;
       this.avgSpeed21 = avgSpeed21;
       this.avgSpeed22 = avgSpeed22;
       this.avgSpeed23 = avgSpeed23;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public DateLookUp getDateLookUp() {
        return this.dateLookUp;
    }
    
    public void setDateLookUp(DateLookUp dateLookUp) {
        this.dateLookUp = dateLookUp;
    }
    public SubRoad getSubRoad() {
        return this.subRoad;
    }
    
    public void setSubRoad(SubRoad subRoad) {
        this.subRoad = subRoad;
    }
    public Double getAvgSpeed00() {
        return this.avgSpeed00;
    }
    
    public void setAvgSpeed00(Double avgSpeed00) {
        this.avgSpeed00 = avgSpeed00;
    }
    public Double getAvgSpeed01() {
        return this.avgSpeed01;
    }
    
    public void setAvgSpeed01(Double avgSpeed01) {
        this.avgSpeed01 = avgSpeed01;
    }
    public Double getAvgSpeed02() {
        return this.avgSpeed02;
    }
    
    public void setAvgSpeed02(Double avgSpeed02) {
        this.avgSpeed02 = avgSpeed02;
    }
    public Double getAvgSpeed03() {
        return this.avgSpeed03;
    }
    
    public void setAvgSpeed03(Double avgSpeed03) {
        this.avgSpeed03 = avgSpeed03;
    }
    public Double getAvgSpeed04() {
        return this.avgSpeed04;
    }
    
    public void setAvgSpeed04(Double avgSpeed04) {
        this.avgSpeed04 = avgSpeed04;
    }
    public Double getAvgSpeed05() {
        return this.avgSpeed05;
    }
    
    public void setAvgSpeed05(Double avgSpeed05) {
        this.avgSpeed05 = avgSpeed05;
    }
    public Double getAvgSpeed06() {
        return this.avgSpeed06;
    }
    
    public void setAvgSpeed06(Double avgSpeed06) {
        this.avgSpeed06 = avgSpeed06;
    }
    public Double getAvgSpeed07() {
        return this.avgSpeed07;
    }
    
    public void setAvgSpeed07(Double avgSpeed07) {
        this.avgSpeed07 = avgSpeed07;
    }
    public Double getAvgSpeed08() {
        return this.avgSpeed08;
    }
    
    public void setAvgSpeed08(Double avgSpeed08) {
        this.avgSpeed08 = avgSpeed08;
    }
    public Double getAvgSpeed09() {
        return this.avgSpeed09;
    }
    
    public void setAvgSpeed09(Double avgSpeed09) {
        this.avgSpeed09 = avgSpeed09;
    }
    public Double getAvgSpeed10() {
        return this.avgSpeed10;
    }
    
    public void setAvgSpeed10(Double avgSpeed10) {
        this.avgSpeed10 = avgSpeed10;
    }
    public Double getAvgSpeed11() {
        return this.avgSpeed11;
    }
    
    public void setAvgSpeed11(Double avgSpeed11) {
        this.avgSpeed11 = avgSpeed11;
    }
    public Double getAvgSpeed12() {
        return this.avgSpeed12;
    }
    
    public void setAvgSpeed12(Double avgSpeed12) {
        this.avgSpeed12 = avgSpeed12;
    }
    public Double getAvgSpeed13() {
        return this.avgSpeed13;
    }
    
    public void setAvgSpeed13(Double avgSpeed13) {
        this.avgSpeed13 = avgSpeed13;
    }
    public Double getAvgSpeed14() {
        return this.avgSpeed14;
    }
    
    public void setAvgSpeed14(Double avgSpeed14) {
        this.avgSpeed14 = avgSpeed14;
    }
    public Double getAvgSpeed15() {
        return this.avgSpeed15;
    }
    
    public void setAvgSpeed15(Double avgSpeed15) {
        this.avgSpeed15 = avgSpeed15;
    }
    public Double getAvgSpeed16() {
        return this.avgSpeed16;
    }
    
    public void setAvgSpeed16(Double avgSpeed16) {
        this.avgSpeed16 = avgSpeed16;
    }
    public Double getAvgSpeed17() {
        return this.avgSpeed17;
    }
    
    public void setAvgSpeed17(Double avgSpeed17) {
        this.avgSpeed17 = avgSpeed17;
    }
    public Double getAvgSpeed18() {
        return this.avgSpeed18;
    }
    
    public void setAvgSpeed18(Double avgSpeed18) {
        this.avgSpeed18 = avgSpeed18;
    }
    public Double getAvgSpeed19() {
        return this.avgSpeed19;
    }
    
    public void setAvgSpeed19(Double avgSpeed19) {
        this.avgSpeed19 = avgSpeed19;
    }
    public Double getAvgSpeed20() {
        return this.avgSpeed20;
    }
    
    public void setAvgSpeed20(Double avgSpeed20) {
        this.avgSpeed20 = avgSpeed20;
    }
    public Double getAvgSpeed21() {
        return this.avgSpeed21;
    }
    
    public void setAvgSpeed21(Double avgSpeed21) {
        this.avgSpeed21 = avgSpeed21;
    }
    public Double getAvgSpeed22() {
        return this.avgSpeed22;
    }
    
    public void setAvgSpeed22(Double avgSpeed22) {
        this.avgSpeed22 = avgSpeed22;
    }
    public Double getAvgSpeed23() {
        return this.avgSpeed23;
    }
    
    public void setAvgSpeed23(Double avgSpeed23) {
        this.avgSpeed23 = avgSpeed23;
    }




}


