package servicelayer.server.dal.pojos;
// Generated Jun 12, 2014 10:23:42 PM by Hibernate Tools 3.6.0



/**
 * HourlyUserRecords generated by hbm2java
 */
public class HourlyUserRecords  implements java.io.Serializable {


     private Integer id;
     private User user;
     private int noOfSnapshots;
     private int hour;

    public HourlyUserRecords() {
    }

    public HourlyUserRecords(User user, int noOfSnapshots, int hour) {
       this.user = user;
       this.noOfSnapshots = noOfSnapshots;
       this.hour = hour;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public int getNoOfSnapshots() {
        return this.noOfSnapshots;
    }
    
    public void setNoOfSnapshots(int noOfSnapshots) {
        this.noOfSnapshots = noOfSnapshots;
    }
    public int getHour() {
        return this.hour;
    }
    
    public void setHour(int hour) {
        this.hour = hour;
    }




}


