package servicelayer.server.dal.pojos;
// Generated Jun 12, 2014 10:23:42 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * MainPoint generated by hbm2java
 */
public class MainPoint  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String displayNameAr;
     private String displayNameEn;
     private String imgUrl;
     private double x;
     private double y;
     private Set routesForDestId = new HashSet(0);
     private Set routesForSrcId = new HashSet(0);

    public MainPoint() {
    }

	
    public MainPoint(double x, double y) {
        this.x = x;
        this.y = y;
    }
    public MainPoint(String name, String displayNameAr, String displayNameEn, String imgUrl, double x, double y, Set routesForDestId, Set routesForSrcId) {
       this.name = name;
       this.displayNameAr = displayNameAr;
       this.displayNameEn = displayNameEn;
       this.imgUrl = imgUrl;
       this.x = x;
       this.y = y;
       this.routesForDestId = routesForDestId;
       this.routesForSrcId = routesForSrcId;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDisplayNameAr() {
        return this.displayNameAr;
    }
    
    public void setDisplayNameAr(String displayNameAr) {
        this.displayNameAr = displayNameAr;
    }
    public String getDisplayNameEn() {
        return this.displayNameEn;
    }
    
    public void setDisplayNameEn(String displayNameEn) {
        this.displayNameEn = displayNameEn;
    }
    public String getImgUrl() {
        return this.imgUrl;
    }
    
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl;
    }
    public double getX() {
        return this.x;
    }
    
    public void setX(double x) {
        this.x = x;
    }
    public double getY() {
        return this.y;
    }
    
    public void setY(double y) {
        this.y = y;
    }
    public Set getRoutesForDestId() {
        return this.routesForDestId;
    }
    
    public void setRoutesForDestId(Set routesForDestId) {
        this.routesForDestId = routesForDestId;
    }
    public Set getRoutesForSrcId() {
        return this.routesForSrcId;
    }
    
    public void setRoutesForSrcId(Set routesForSrcId) {
        this.routesForSrcId = routesForSrcId;
    }




}


