package servicelayer.server.dal.pojos;
// Generated Jun 12, 2014 10:23:42 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * ModeLookUp generated by hbm2java
 */
public class ModeLookUp  implements java.io.Serializable {


     private int modeId;
     private String modeValue;
     private Set pendingUsers = new HashSet(0);
     private Set users = new HashSet(0);

    public ModeLookUp() {
    }

	
    public ModeLookUp(int modeId, String modeValue) {
        this.modeId = modeId;
        this.modeValue = modeValue;
    }
    public ModeLookUp(int modeId, String modeValue, Set pendingUsers, Set users) {
       this.modeId = modeId;
       this.modeValue = modeValue;
       this.pendingUsers = pendingUsers;
       this.users = users;
    }
   
    public int getModeId() {
        return this.modeId;
    }
    
    public void setModeId(int modeId) {
        this.modeId = modeId;
    }
    public String getModeValue() {
        return this.modeValue;
    }
    
    public void setModeValue(String modeValue) {
        this.modeValue = modeValue;
    }
    public Set getPendingUsers() {
        return this.pendingUsers;
    }
    
    public void setPendingUsers(Set pendingUsers) {
        this.pendingUsers = pendingUsers;
    }
    public Set getUsers() {
        return this.users;
    }
    
    public void setUsers(Set users) {
        this.users = users;
    }




}


