package servicelayer.server.dal.pojos;
// Generated Jun 12, 2014 10:23:42 PM by Hibernate Tools 3.6.0



/**
 * PageHits generated by hbm2java
 */
public class PageHits  implements java.io.Serializable {


     private Integer id;
     private User user;
     private String pageName;
     private String appVerId;
     private String osId;
     private String imie;

    public PageHits() {
    }

	
    public PageHits(String pageName) {
        this.pageName = pageName;
    }
    public PageHits(User user, String pageName, String appVerId, String osId, String imie) {
       this.user = user;
       this.pageName = pageName;
       this.appVerId = appVerId;
       this.osId = osId;
       this.imie = imie;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getPageName() {
        return this.pageName;
    }
    
    public void setPageName(String pageName) {
        this.pageName = pageName;
    }
    public String getAppVerId() {
        return this.appVerId;
    }
    
    public void setAppVerId(String appVerId) {
        this.appVerId = appVerId;
    }
    public String getOsId() {
        return this.osId;
    }
    
    public void setOsId(String osId) {
        this.osId = osId;
    }
    public String getImie() {
        return this.imie;
    }
    
    public void setImie(String imie) {
        this.imie = imie;
    }




}


