package servicelayer.server.dal.pojos;
// Generated Jun 12, 2014 10:23:42 PM by Hibernate Tools 3.6.0



/**
 * PendingUser generated by hbm2java
 */
public class PendingUser  implements java.io.Serializable {


     private Integer id;
     private FuelLookUp fuelLookUp;
     private ModeLookUp modeLookUp;
     private String name;
     private String mobile;
     private String email;
     private String userToken;
     private int tokenType;
     private String verificationCode;

    public PendingUser() {
    }

	
    public PendingUser(int tokenType) {
        this.tokenType = tokenType;
    }
    public PendingUser(FuelLookUp fuelLookUp, ModeLookUp modeLookUp, String name, String mobile, String email, String userToken, int tokenType, String verificationCode) {
       this.fuelLookUp = fuelLookUp;
       this.modeLookUp = modeLookUp;
       this.name = name;
       this.mobile = mobile;
       this.email = email;
       this.userToken = userToken;
       this.tokenType = tokenType;
       this.verificationCode = verificationCode;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public FuelLookUp getFuelLookUp() {
        return this.fuelLookUp;
    }
    
    public void setFuelLookUp(FuelLookUp fuelLookUp) {
        this.fuelLookUp = fuelLookUp;
    }
    public ModeLookUp getModeLookUp() {
        return this.modeLookUp;
    }
    
    public void setModeLookUp(ModeLookUp modeLookUp) {
        this.modeLookUp = modeLookUp;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getUserToken() {
        return this.userToken;
    }
    
    public void setUserToken(String userToken) {
        this.userToken = userToken;
    }
    public int getTokenType() {
        return this.tokenType;
    }
    
    public void setTokenType(int tokenType) {
        this.tokenType = tokenType;
    }
    public String getVerificationCode() {
        return this.verificationCode;
    }
    
    public void setVerificationCode(String verificationCode) {
        this.verificationCode = verificationCode;
    }




}


