package servicelayer.server.dal.pojos;
// Generated Jun 12, 2014 10:23:42 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Privileges generated by hbm2java
 */
public class Privileges  implements java.io.Serializable {


     private Integer id;
     private String description;
     private Set roleses = new HashSet(0);

    public Privileges() {
    }

	
    public Privileges(String description) {
        this.description = description;
    }
    public Privileges(String description, Set roleses) {
       this.description = description;
       this.roleses = roleses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set getRoleses() {
        return this.roleses;
    }
    
    public void setRoleses(Set roleses) {
        this.roleses = roleses;
    }




}


