package servicelayer.server.dal.pojos;
// Generated Jun 12, 2014 10:23:42 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * ReportTypeLookUp generated by hbm2java
 */
public class ReportTypeLookUp  implements java.io.Serializable {


     private int reportTypeId;
     private String reportTypeValue;
     private Set userRoadReports = new HashSet(0);
     private Set adminRoadReports = new HashSet(0);

    public ReportTypeLookUp() {
    }

	
    public ReportTypeLookUp(int reportTypeId, String reportTypeValue) {
        this.reportTypeId = reportTypeId;
        this.reportTypeValue = reportTypeValue;
    }
    public ReportTypeLookUp(int reportTypeId, String reportTypeValue, Set userRoadReports, Set adminRoadReports) {
       this.reportTypeId = reportTypeId;
       this.reportTypeValue = reportTypeValue;
       this.userRoadReports = userRoadReports;
       this.adminRoadReports = adminRoadReports;
    }
   
    public int getReportTypeId() {
        return this.reportTypeId;
    }
    
    public void setReportTypeId(int reportTypeId) {
        this.reportTypeId = reportTypeId;
    }
    public String getReportTypeValue() {
        return this.reportTypeValue;
    }
    
    public void setReportTypeValue(String reportTypeValue) {
        this.reportTypeValue = reportTypeValue;
    }
    public Set getUserRoadReports() {
        return this.userRoadReports;
    }
    
    public void setUserRoadReports(Set userRoadReports) {
        this.userRoadReports = userRoadReports;
    }
    public Set getAdminRoadReports() {
        return this.adminRoadReports;
    }
    
    public void setAdminRoadReports(Set adminRoadReports) {
        this.adminRoadReports = adminRoadReports;
    }




}


