package servicelayer.server.dal.pojos;
// Generated Jun 12, 2014 10:23:42 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Road generated by hbm2java
 */
public class Road  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String displayNameAr;
     private String displayNameEn;
     private Set subRoutes = new HashSet(0);
     private Set subRoads = new HashSet(0);
     private Set userRoadReports = new HashSet(0);
     private Set adminRoadReports = new HashSet(0);

    public Road() {
    }

    public Road(String name, String displayNameAr, String displayNameEn, Set subRoutes, Set subRoads, Set userRoadReports, Set adminRoadReports) {
       this.name = name;
       this.displayNameAr = displayNameAr;
       this.displayNameEn = displayNameEn;
       this.subRoutes = subRoutes;
       this.subRoads = subRoads;
       this.userRoadReports = userRoadReports;
       this.adminRoadReports = adminRoadReports;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDisplayNameAr() {
        return this.displayNameAr;
    }
    
    public void setDisplayNameAr(String displayNameAr) {
        this.displayNameAr = displayNameAr;
    }
    public String getDisplayNameEn() {
        return this.displayNameEn;
    }
    
    public void setDisplayNameEn(String displayNameEn) {
        this.displayNameEn = displayNameEn;
    }
    public Set getSubRoutes() {
        return this.subRoutes;
    }
    
    public void setSubRoutes(Set subRoutes) {
        this.subRoutes = subRoutes;
    }
    public Set getSubRoads() {
        return this.subRoads;
    }
    
    public void setSubRoads(Set subRoads) {
        this.subRoads = subRoads;
    }
    public Set getUserRoadReports() {
        return this.userRoadReports;
    }
    
    public void setUserRoadReports(Set userRoadReports) {
        this.userRoadReports = userRoadReports;
    }
    public Set getAdminRoadReports() {
        return this.adminRoadReports;
    }
    
    public void setAdminRoadReports(Set adminRoadReports) {
        this.adminRoadReports = adminRoadReports;
    }




}


