package servicelayer.server.dal.pojos;
// Generated Jun 12, 2014 10:23:42 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Roles generated by hbm2java
 */
public class Roles  implements java.io.Serializable {


     private Integer roleId;
     private String roleName;
     private Set admins = new HashSet(0);
     private Set privilegeses = new HashSet(0);

    public Roles() {
    }

	
    public Roles(String roleName) {
        this.roleName = roleName;
    }
    public Roles(String roleName, Set admins, Set privilegeses) {
       this.roleName = roleName;
       this.admins = admins;
       this.privilegeses = privilegeses;
    }
   
    public Integer getRoleId() {
        return this.roleId;
    }
    
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }
    public String getRoleName() {
        return this.roleName;
    }
    
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }
    public Set getAdmins() {
        return this.admins;
    }
    
    public void setAdmins(Set admins) {
        this.admins = admins;
    }
    public Set getPrivilegeses() {
        return this.privilegeses;
    }
    
    public void setPrivilegeses(Set privilegeses) {
        this.privilegeses = privilegeses;
    }




}


