package servicelayer.server.dal.pojos;
// Generated Jun 12, 2014 10:23:42 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Route generated by hbm2java
 */
public class Route  implements java.io.Serializable {


     private Integer id;
     private MainPoint mainPointBySrcId;
     private MainPoint mainPointByDestId;
     private String name;
     private String displayNameAr;
     private String displayNameEn;
     private Set subRoutes = new HashSet(0);

    public Route() {
    }

	
    public Route(MainPoint mainPointBySrcId, MainPoint mainPointByDestId) {
        this.mainPointBySrcId = mainPointBySrcId;
        this.mainPointByDestId = mainPointByDestId;
    }
    public Route(MainPoint mainPointBySrcId, MainPoint mainPointByDestId, String name, String displayNameAr, String displayNameEn, Set subRoutes) {
       this.mainPointBySrcId = mainPointBySrcId;
       this.mainPointByDestId = mainPointByDestId;
       this.name = name;
       this.displayNameAr = displayNameAr;
       this.displayNameEn = displayNameEn;
       this.subRoutes = subRoutes;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public MainPoint getMainPointBySrcId() {
        return this.mainPointBySrcId;
    }
    
    public void setMainPointBySrcId(MainPoint mainPointBySrcId) {
        this.mainPointBySrcId = mainPointBySrcId;
    }
    public MainPoint getMainPointByDestId() {
        return this.mainPointByDestId;
    }
    
    public void setMainPointByDestId(MainPoint mainPointByDestId) {
        this.mainPointByDestId = mainPointByDestId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDisplayNameAr() {
        return this.displayNameAr;
    }
    
    public void setDisplayNameAr(String displayNameAr) {
        this.displayNameAr = displayNameAr;
    }
    public String getDisplayNameEn() {
        return this.displayNameEn;
    }
    
    public void setDisplayNameEn(String displayNameEn) {
        this.displayNameEn = displayNameEn;
    }
    public Set getSubRoutes() {
        return this.subRoutes;
    }
    
    public void setSubRoutes(Set subRoutes) {
        this.subRoutes = subRoutes;
    }




}


