package servicelayer.server.dal.pojos;
// Generated Jun 12, 2014 10:23:42 PM by Hibernate Tools 3.6.0



/**
 * SubRoute generated by hbm2java
 */
public class SubRoute  implements java.io.Serializable {


     private Integer id;
     private Route route;
     private Road road;
     private int orderr;

    public SubRoute() {
    }

    public SubRoute(Route route, Road road, int orderr) {
       this.route = route;
       this.road = road;
       this.orderr = orderr;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Route getRoute() {
        return this.route;
    }
    
    public void setRoute(Route route) {
        this.route = route;
    }
    public Road getRoad() {
        return this.road;
    }
    
    public void setRoad(Road road) {
        this.road = road;
    }
    public int getOrderr() {
        return this.orderr;
    }
    
    public void setOrderr(int orderr) {
        this.orderr = orderr;
    }




}


