package servicelayer.server.dal.pojos;
// Generated Jun 12, 2014 10:23:42 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer id;
     private CarListLookUp carListLookUp;
     private FuelLookUp fuelLookUp;
     private ModeLookUp modeLookUp;
     private String name;
     private String mobile;
     private String email;
     private String userToken;
     private int tokenType;
     private byte[] photo;
     private Set snapshots = new HashSet(0);
     private Set outsideSnapShots = new HashSet(0);
     private Set userRoadReports = new HashSet(0);
     private Set dailyWinners = new HashSet(0);
     private Set pageHitses = new HashSet(0);
     private Set hourlyUserRecordses = new HashSet(0);

    public User() {
    }

	
    public User(int tokenType) {
        this.tokenType = tokenType;
    }
    public User(CarListLookUp carListLookUp, FuelLookUp fuelLookUp, ModeLookUp modeLookUp, String name, String mobile, String email, String userToken, int tokenType, byte[] photo, Set snapshots, Set outsideSnapShots, Set userRoadReports, Set dailyWinners, Set pageHitses, Set hourlyUserRecordses) {
       this.carListLookUp = carListLookUp;
       this.fuelLookUp = fuelLookUp;
       this.modeLookUp = modeLookUp;
       this.name = name;
       this.mobile = mobile;
       this.email = email;
       this.userToken = userToken;
       this.tokenType = tokenType;
       this.photo = photo;
       this.snapshots = snapshots;
       this.outsideSnapShots = outsideSnapShots;
       this.userRoadReports = userRoadReports;
       this.dailyWinners = dailyWinners;
       this.pageHitses = pageHitses;
       this.hourlyUserRecordses = hourlyUserRecordses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public CarListLookUp getCarListLookUp() {
        return this.carListLookUp;
    }
    
    public void setCarListLookUp(CarListLookUp carListLookUp) {
        this.carListLookUp = carListLookUp;
    }
    public FuelLookUp getFuelLookUp() {
        return this.fuelLookUp;
    }
    
    public void setFuelLookUp(FuelLookUp fuelLookUp) {
        this.fuelLookUp = fuelLookUp;
    }
    public ModeLookUp getModeLookUp() {
        return this.modeLookUp;
    }
    
    public void setModeLookUp(ModeLookUp modeLookUp) {
        this.modeLookUp = modeLookUp;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getUserToken() {
        return this.userToken;
    }
    
    public void setUserToken(String userToken) {
        this.userToken = userToken;
    }
    public int getTokenType() {
        return this.tokenType;
    }
    
    public void setTokenType(int tokenType) {
        this.tokenType = tokenType;
    }
    public byte[] getPhoto() {
        return this.photo;
    }
    
    public void setPhoto(byte[] photo) {
        this.photo = photo;
    }
    public Set getSnapshots() {
        return this.snapshots;
    }
    
    public void setSnapshots(Set snapshots) {
        this.snapshots = snapshots;
    }
    public Set getOutsideSnapShots() {
        return this.outsideSnapShots;
    }
    
    public void setOutsideSnapShots(Set outsideSnapShots) {
        this.outsideSnapShots = outsideSnapShots;
    }
    public Set getUserRoadReports() {
        return this.userRoadReports;
    }
    
    public void setUserRoadReports(Set userRoadReports) {
        this.userRoadReports = userRoadReports;
    }
    public Set getDailyWinners() {
        return this.dailyWinners;
    }
    
    public void setDailyWinners(Set dailyWinners) {
        this.dailyWinners = dailyWinners;
    }
    public Set getPageHitses() {
        return this.pageHitses;
    }
    
    public void setPageHitses(Set pageHitses) {
        this.pageHitses = pageHitses;
    }
    public Set getHourlyUserRecordses() {
        return this.hourlyUserRecordses;
    }
    
    public void setHourlyUserRecordses(Set hourlyUserRecordses) {
        this.hourlyUserRecordses = hourlyUserRecordses;
    }




}


