package servicelayer.server.dal.pojos;
// Generated Jun 12, 2014 10:23:42 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * UserRoadReport generated by hbm2java
 */
public class UserRoadReport  implements java.io.Serializable {


     private Integer id;
     private User user;
     private Road road;
     private ReportTypeLookUp reportTypeLookUp;
     private Date timeStamp;

    public UserRoadReport() {
    }

	
    public UserRoadReport(User user, Road road, ReportTypeLookUp reportTypeLookUp) {
        this.user = user;
        this.road = road;
        this.reportTypeLookUp = reportTypeLookUp;
    }
    public UserRoadReport(User user, Road road, ReportTypeLookUp reportTypeLookUp, Date timeStamp) {
       this.user = user;
       this.road = road;
       this.reportTypeLookUp = reportTypeLookUp;
       this.timeStamp = timeStamp;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Road getRoad() {
        return this.road;
    }
    
    public void setRoad(Road road) {
        this.road = road;
    }
    public ReportTypeLookUp getReportTypeLookUp() {
        return this.reportTypeLookUp;
    }
    
    public void setReportTypeLookUp(ReportTypeLookUp reportTypeLookUp) {
        this.reportTypeLookUp = reportTypeLookUp;
    }
    public Date getTimeStamp() {
        return this.timeStamp;
    }
    
    public void setTimeStamp(Date timeStamp) {
        this.timeStamp = timeStamp;
    }




}


